#!/usr/bin/env python3
"""
Reproducible derivation of all Montgomery + FFT parameters for the new
libff base field Fp192 (PLUM's ~199-bit prime), to back
libff/algebra/curves/fp192/fp192_fields.cpp.

Usage:
    python3 scripts/compute_fp192_constants.py

Field layout (must match src/primitives/field/p192.rs):
    p   = 2^64 * p_0 + 1           (199-bit, prime)
    p_0 = 25953665385296571073907086806836816188273   (prime; the substitute,
          because the paper's printed p_0 is composite, smallest factor 97)
    R   = 2^256                    (4 x 64-bit Montgomery limbs)

Unlike Fp127 (a Mersenne prime that needed an Fp2 extension for a smooth FFT
subgroup), Fp192 has base-field 2-adicity s = 64, so Aurora runs over the
BASE field directly. No Fp2 / Frobenius / non_residue machinery is emitted.

This script is self-verifying: every constant is cross-checked against its
defining field-theoretic property (asserts). If it prints, Stage-1 field math
is correct independent of the C++ build.
"""

# --- p from src/primitives/field/p192.rs::MODULUS_LIMBS (little-endian u64x4) ---
MODULUS_LIMBS = [
    0x0000_0000_0000_0001,
    0x7bbd_7e10_d66d_1371,
    0x455e_221a_5f68_af51,
    0x0000_0000_0000_004c,
]
p = sum(limb << (64 * i) for i, limb in enumerate(MODULUS_LIMBS))

# p_0 from p192.rs:33 (claimed prime); we re-verify it below.
P0_CLAIMED = 25953665385296571073907086806836816188273


def miller_rabin(n, bases=(2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37,
                           41, 43, 47, 53, 59, 61, 67, 71, 73, 79)):
    if n < 2:
        return False
    d, s = n - 1, 0
    while d % 2 == 0:
        d //= 2
        s += 1
    for a in bases:
        if a % n == 0:
            continue
        x = pow(a, d, n)
        if x in (1, n - 1):
            continue
        for _ in range(s - 1):
            x = (x * x) % n
            if x == n - 1:
                break
        else:
            return False
    return True


def legendre(a, p):
    a %= p
    if a == 0:
        return 0
    r = pow(a, (p - 1) // 2, p)
    return -1 if r == p - 1 else 1


def main():
    # ---- p basics, cross-checked against p192.rs constants ----
    assert p.bit_length() == 199, f"MODULUS_BITS should be 199, got {p.bit_length()}"
    assert miller_rabin(p), "p must be prime"

    pm1 = p - 1
    s, t = 0, pm1
    while t % 2 == 0:
        t //= 2
        s += 1
    assert s == 64, f"TWO_ADICITY should be 64, got {s}"
    assert t == P0_CLAIMED, "t = (p-1)/2^64 must equal the claimed p_0"
    assert miller_rabin(t), "p_0 must be prime (so p-1 factors as 2^64 * p_0)"

    # t = 256 | p-1 (power-residue PRF parameter)
    assert pm1 % 256 == 0, "t_residue = 256 must divide p-1"

    # ---- Montgomery constants (n = 4 limbs, R = 2^256) ----
    R = 1 << 256
    W = 1 << 64
    Rsq = (R * R) % p
    Rcb = (R * R * R) % p
    inv = (-pow(p % W, -1, W)) % W          # -p^{-1} mod 2^64
    assert (p * inv) % W == (W - 1), "inv must satisfy p*inv = -1 (mod 2^64)"

    # ---- prime factorization of |Fp^*| = p-1 = 2^64 * p_0 ----
    prime_factors = {2, t}                  # t == p_0, prime

    # ---- smallest primitive root g of Fp^* ----
    g = None
    for cand in range(2, 1000):
        if all(pow(cand, pm1 // q, p) != 1 for q in prime_factors):
            g = cand
            break
    assert g is not None, "no primitive root found below 1000"
    # verify true generator (order exactly p-1)
    assert pow(g, pm1, p) == 1
    for q in prime_factors:
        assert pow(g, pm1 // q, p) != 1

    # ---- root_of_unity = g^t : a primitive 2^s-th root of unity ----
    rou = pow(g, t, p)
    assert pow(rou, 1 << s, p) == 1, "rou^(2^s) must be 1"
    assert pow(rou, 1 << (s - 1), p) != 1, "rou must have order exactly 2^s"

    # ---- nqr (smallest quadratic non-residue) and nqr_to_t ----
    nqr = next(a for a in range(2, 1000) if legendre(a, p) == -1)
    nqr_to_t = pow(nqr, t, p)
    chk = nqr_to_t
    for _ in range(s):
        chk = (chk * chk) % p
    assert chk == 1, "nqr_to_t^(2^s) must be 1"

    euler = pm1 // 2
    t_minus_1_over_2 = (t - 1) // 2

    # ---- emit, in the order the fp192_fields.cpp init will consume ----
    def hexlimbs(x):
        return "0x" + format(x, "x")

    print("// Generated by scripts/compute_fp192_constants.py")
    print(f"// p   = {p}")
    print(f"// p   = {hexlimbs(p)}")
    print(f"// p_0 = {t}   (prime; p-1 = 2^64 * p_0)")
    print(f"// s (2-adicity) = {s}")
    print()
    print(f"fp192_Fq::modulus                  = {p}")
    print(f"fp192_Fq::Rsquared                 = {Rsq}")
    print(f"fp192_Fq::Rcubed                   = {Rcb}")
    print(f"fp192_Fq::inv (64-bit)             = 0x{inv:016x}")
    print(f"fp192_Fq::num_bits                 = {p.bit_length()}")
    print(f"fp192_Fq::euler = (p-1)/2          = {euler}")
    print(f"fp192_Fq::s                        = {s}")
    print(f"fp192_Fq::t = (p-1)/2^s            = {t}")
    print(f"fp192_Fq::t_minus_1_over_2         = {t_minus_1_over_2}")
    print(f"fp192_Fq::multiplicative_generator = {g}   (verified primitive root of Fp^*)")
    print(f"fp192_Fq::root_of_unity            = {rou}   (= g^t, primitive 2^{s}-th root)")
    print(f"fp192_Fq::nqr                      = {nqr}")
    print(f"fp192_Fq::nqr_to_t                 = {nqr_to_t}")
    print()
    print("// All asserts passed: field math verified independent of the C++ build.")


if __name__ == "__main__":
    main()
