#!/usr/bin/env python3
"""
Reproducible derivation of all Montgomery + Fp/Fp2 parameters for
libff/algebra/curves/fp127/fp127_fields.cpp.

Usage:
    python3 scripts/compute_fp127_constants.py

Produces the exact constants hard-coded in the libff init file. Re-run this
script if the prime or the Fp2 non-residue is ever changed.

Field layout (must match src/loquat/field_p127.rs):
    p         = 2^127 - 1           (Mersenne, prime)
    Fp2       = Fp[U] / (U^2 - 3)   (non-residue = 3)
    witness byte layout: (c0_le_u128 || c1_le_u128) = 32 bytes per Fp2 element
"""

p = (1 << 127) - 1
NON_RESIDUE = 3  # matches src/loquat/field_p127.rs::qnr()


def legendre(a: int, p: int) -> int:
    a %= p
    if a == 0:
        return 0
    r = pow(a, (p - 1) // 2, p)
    return -1 if r == p - 1 else (1 if r == 1 else 0)


def miller_rabin(n: int, bases=(2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37)) -> bool:
    if n < 2:
        return False
    d, s = n - 1, 0
    while d % 2 == 0:
        d //= 2
        s += 1
    for a in bases:
        if a % n == 0:
            continue
        x = pow(a, d, n)
        if x in (1, n - 1):
            continue
        for _ in range(s - 1):
            x = (x * x) % n
            if x == n - 1:
                break
        else:
            return False
    return True


def fp2_mul(x, y, nres=NON_RESIDUE):
    return ((x[0] * y[0] + nres * x[1] * y[1]) % p,
            (x[0] * y[1] + x[1] * y[0]) % p)


def fp2_pow(x, e, nres=NON_RESIDUE):
    r = (1, 0)
    b = x
    while e > 0:
        if e & 1:
            r = fp2_mul(r, b, nres)
        b = fp2_mul(b, b, nres)
        e >>= 1
    return r


def main():
    assert miller_rabin(p), "p must be prime"
    assert p % 6 == 1, "libff Fp2_model assumes p ≡ 1 (mod 6)"
    assert legendre(NON_RESIDUE, p) == -1, "non_residue must be a QNR mod p"

    # Montgomery (n=2 64-bit limbs, R = 2^128)
    R = 1 << 128
    W = 1 << 64
    Rsq = (R * R) % p
    Rcb = (R * R * R) % p
    p_mod_W = p % W
    inv = (-pow(p_mod_W, -1, W)) % W

    # Fp 2-adicity
    pm1 = p - 1
    s, t = 0, pm1
    while t % 2 == 0:
        t //= 2
        s += 1

    # Fp2 2-adicity
    pp_m1 = p * p - 1
    s2, t2 = 0, pp_m1
    while t2 % 2 == 0:
        t2 //= 2
        s2 += 1

    # Fp2 nqr: first (a,b) with legendre(a^2 - nres*b^2, p) == -1
    nqr_ab = None
    for a in range(4):
        for b in range(4):
            if a == 0 and b == 0:
                continue
            norm = (a * a - NON_RESIDUE * b * b) % p
            if legendre(norm, p) == -1:
                nqr_ab = (a, b)
                break
        if nqr_ab is not None:
            break
    nqr_to_t = fp2_pow(nqr_ab, t2)

    # Sanity: nqr_to_t^(2^s2) == 1
    chk = nqr_to_t
    for _ in range(s2):
        chk = fp2_mul(chk, chk)
    assert chk == (1, 0), "nqr_to_t^(2^s) must be 1 in Fp2"

    # Emit in the same order as fp127_fields.cpp
    print(f"// Generated by scripts/compute_fp127_constants.py")
    print(f"// p = 2^127 - 1 = {p}")
    print(f"Fq::modulus                 = {p}")
    print(f"Fq::Rsquared                = {Rsq}")
    print(f"Fq::Rcubed                  = {Rcb}")
    print(f"Fq::inv (64-bit)            = 0x{inv:016x}")
    print(f"Fq::num_bits                = {p.bit_length()}")
    print(f"Fq::euler = (p-1)/2         = {(p - 1) // 2}")
    print(f"Fq::s                       = {s}")
    print(f"Fq::t                       = {t}")
    print(f"Fq::t_minus_1_over_2        = {(t - 1) // 2}")
    print(f"Fq::multiplicative_generator = {NON_RESIDUE}  (smallest QNR)")
    print(f"Fq::root_of_unity           = {p - 1}  (= -1, since s = {s})")
    print(f"Fq::nqr                     = {NON_RESIDUE}")
    print(f"Fq::nqr_to_t                = {pow(NON_RESIDUE, t, p)}")
    print()
    print(f"Fq2::non_residue            = {NON_RESIDUE}")
    print(f"Fq2::s                      = {s2}")
    print(f"Fq2::t                      = {t2}")
    print(f"Fq2::euler = (p^2-1)/2      = {pp_m1 // 2}")
    print(f"Fq2::t_minus_1_over_2       = {(t2 - 1) // 2}")
    print(f"Fq2::Frobenius_coeffs_c1[0] = 1")
    print(f"Fq2::Frobenius_coeffs_c1[1] = {pow(NON_RESIDUE, (p - 1) // 2, p)}")
    print(f"Fq2::nqr                    = ({nqr_ab[0]}, {nqr_ab[1]})")
    print(f"Fq2::nqr_to_t               = ({nqr_to_t[0]}, {nqr_to_t[1]})")

    # --- Primitive root of Fp2^* and corresponding root_of_unity (Aurora needs these) ---
    # |Fp2^*| = p^2 - 1 = 2^128 * (2^126 - 1). Factor 2^126 - 1 by trial division +
    # Miller-Rabin on the residual; verified factorization:
    #   2^126 - 1 = 3^3 * 7^2 * 19 * 43 * 73 * 127 * 337 * 5419 * 92737 * 649657 * 77158673929
    order = p * p - 1
    odd = (1 << 126) - 1
    prime_factors = {2}
    x = odd
    q = 3
    while q * q <= x:
        while x % q == 0:
            prime_factors.add(q)
            x //= q
        q += 2
    if x > 1:
        assert miller_rabin(x), f"residual {x} must be prime"
        prime_factors.add(x)

    # Find smallest (a, b) such that g = a + b*U is a primitive root of Fp2^*.
    g_ab = None
    for a in range(6):
        for b in range(6):
            if a == 0 and b == 0:
                continue
            g = (a, b)
            primitive = True
            for qq in prime_factors:
                if fp2_pow(g, order // qq) == (1, 0):
                    primitive = False
                    break
            if primitive:
                g_ab = (a, b)
                break
        if g_ab is not None:
            break
    assert g_ab is not None, "no primitive root found in small search space"
    assert fp2_pow(g_ab, order) == (1, 0)

    # root_of_unity = g^t (primitive 2^s-th root of unity in Fp2).
    rou = fp2_pow(g_ab, t2)
    print()
    print(f"Fq2::multiplicative_generator = ({g_ab[0]}, {g_ab[1]})  (primitive root)")
    print(f"Fq2::root_of_unity            = ({rou[0]}, {rou[1]})  (= g^t, primitive 2^{s2}-th root)")


if __name__ == "__main__":
    main()
